name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.1.1'
      SERVERPOD_PASSWORD_database: 'zItOn-rIkf-LCW82IeTPv8EgMaphtDSS'
      SERVERPOD_PASSWORD_redis: '7i1Pcli7vCYPywlmPS_uqZyace_dEhUw'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: daypilot_backend_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: daypilot_backend_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: daypilot_backend_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: daypilot_backend_server
        run: serverpod generate

      - name: Run tests
        working-directory: daypilot_backend_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: daypilot_backend_server
        run: docker compose down -v
